### ISSUE TITLE
Running multiple single websites using docker (compose)

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/docker-compose-wordpress#3]
Please do not confuse this with running "WordPress Multisite". It is covered in #4 

**Test case**

- [x] Create 3 websites with EasyEngine style file layout such as `/var/www/example.com`, `/var/www/foo.com`, `/var/www/bar.com`, etc
- [x] All websites must be publicly accessible in their own domain/subdomain. Always on port 80.

**Requirements**
- This will need some kind of host/guest port mapping. Docker networking 💪
- It might need some kind of nginx proxying from host

**Comment by mbtamuli** [comment]
Issue to be closed after testing.

[Multiple Sites](https://github.com/EasyEngine/docker-compose-wordpress/tree/master/multiple-sites) is ready for testing. The test cases are in the description. After testing comment on this issue.

**Comment by mbtamuli** [comment]
Outdated version of ee4
